import {useState} from 'react';
import {Link} from 'react-router-dom';
import {validateArticle} from '../lib/articleSchema.js';
import {StoryImage,Video} from '../components/EditorialSections.jsx';
import '../styles/aura-editorial.css';
import '../styles/admin-articles.css';
const KEY='aura-article-draft-v1';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Atlantic/Canary',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const blank=()=>({slug:'',title:'',summary:'',category:'Headlines',articleType:'News',sources:[],date:today(),body:[],source:'',sourceUrl:'',featured:true,priority:50,youtubeId:null,videoUrl:'',image:{src:'',alt:'',credit:'',caption:'',sourceUrl:''}});
function initial(){try{return JSON.parse(localStorage.getItem(KEY))||blank();}catch{return blank();}}
export default function AdminArticles(){
 const [article,setArticle]=useState(initial);const [edition,setEdition]=useState(null);const [password,setPassword]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [preview,setPreview]=useState(false);const [originalSlug,setOriginalSlug]=useState(null);
 const field=(key,value)=>setArticle(a=>({...a,[key]:value}));const image=(key,value)=>setArticle(a=>({...a,image:{...a.image,[key]:value}}));
 async function load(){setBusy(true);try{const r=await fetch('/api/articles');const data=await r.json();if(!r.ok)throw Error(data.error||'Could not load articles.');setEdition(data);setMessage(data.configured?'Edition loaded. Ready to publish.':'Edition loaded. Publishing connection needs setup. You can save a draft and preview it.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 function saveDraft(){try{localStorage.setItem(KEY,JSON.stringify(article));setMessage('Draft saved on this device. It has not been published.');}catch{setMessage('Could not save your draft. Keep this page open.');}}
 async function publish(e){e.preventDefault();setBusy(true);try{const checked=validateArticle(article);if(originalSlug && checked.slug!==originalSlug)throw Error('Keep the article address unchanged when editing a published story.');const r=await fetch('/api/articles',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${password}`},body:JSON.stringify({article:checked,revision:edition?.revision,mode:originalSlug?'update':'create'})});const data=await r.json();if(!r.ok)throw Error(data.error||'Publishing failed.');setEdition(data);setOriginalSlug(checked.slug);setMessage('Published successfully. The public news feed now reads the saved edition; the site build will also refresh.');localStorage.removeItem(KEY);}catch(e){setMessage(e.message);try{localStorage.setItem(KEY,JSON.stringify(article));}catch{}}finally{setBusy(false);}}
 function pick(slug){const found=edition?.articles.find(a=>a.slug===slug);if(found){setArticle(found);setOriginalSlug(slug);setPreview(false);setMessage('Editing published story. Changes go live only when you publish.');}}
 const input=(label,key,type='text')=><label>{label}<input type={type} required value={article[key]||''} onChange={e=>field(key,e.target.value)} /></label>;
 return <main className="aura-editorial aura-article-admin"><div className="aura-ed-kicker">AURA / Newsroom</div><h1>Publish the fight.</h1><p>Add today’s stories, keep sources attached and choose the headlines readers see first.</p><div className="aura-admin-toolbar"><Link to="/news">View Fight News</Link><Link to="/admin">Admin home</Link><button disabled={busy} onClick={load}>Load published articles</button><button onClick={()=>{setArticle(blank());setOriginalSlug(null);setPreview(false);}}>New article</button></div>
 {message && <p role="status" className="aura-admin-message">{message}</p>}
 {edition && <label className="aura-admin-select">Published articles<select value={originalSlug||''} onChange={e=>pick(e.target.value)}><option value="">Choose a story to edit</option>{edition.articles.map(a=><option value={a.slug} key={a.slug}>{a.date} · {a.title}</option>)}</select></label>}
 <form onSubmit={publish}><div className="aura-admin-fields">{input('Headline','title')}{input('Article address (lowercase-words)','slug')}{input('Category','category')}<label>Article type<select value={article.articleType||'News'} onChange={e=>field('articleType',e.target.value)}><option>News</option><option>Analysis</option><option>Opinion</option></select></label>{input('Publication date','date','date')}{input('Homepage priority (0–100)','priority','number')}<label className="wide">Short introduction<textarea required value={article.summary} onChange={e=>field('summary',e.target.value)} /></label><label className="wide">Article text (separate paragraphs with a blank line)<textarea className="article-text" required value={article.body.join('\n\n')} onChange={e=>field('body',e.target.value.split(/\n\s*\n/))} /></label>{input('Original source name','source')}{input('Original report link','sourceUrl','url')}<label className="wide">Additional sources (one per line: name | HTTPS link)<textarea value={(article.sources||[]).map(s=>`${s.name} | ${s.url}`).join('\n')} onChange={e=>field('sources',e.target.value.split('\n').filter(line=>line.trim()).map(line=>{const at=line.indexOf('|');return {name:at<0?line.trim():line.slice(0,at).trim(),url:at<0?'':line.slice(at+1).trim()};}))} /></label><label>Image link<input type="url" required value={article.image.src} onChange={e=>image('src',e.target.value)} /></label><label>Image credit<input required value={article.image.credit} onChange={e=>image('credit',e.target.value)} /></label><label>Accurate image description<input required value={article.image.alt} onChange={e=>image('alt',e.target.value)} /></label><label>Image caption (include date for archive photos)<input value={article.image.caption||''} onChange={e=>image('caption',e.target.value)} /></label><label>Image source page (optional)<input type="url" value={article.image.sourceUrl||''} onChange={e=>image('sourceUrl',e.target.value)} /></label><label>YouTube link (optional)<input type="url" value={article.videoUrl||''} onChange={e=>{const value=e.target.value;let id=null;try{const u=new URL(value);if(u.hostname==='youtu.be')id=u.pathname.slice(1);else if(['www.youtube.com','youtube.com','m.youtube.com'].includes(u.hostname))id=u.searchParams.get('v')||u.pathname.match(/\/(?:shorts|embed)\/([\w-]{11})/)?.[1];}catch{}setArticle(a=>({...a,videoUrl:value,youtubeId:id}));}} /></label><label className="aura-admin-checkbox"><input type="checkbox" checked={article.featured===true} onChange={e=>field('featured',e.target.checked)} />Feature on homepage</label></div>
 <div className="aura-admin-toolbar"><button type="button" onClick={saveDraft}>Save draft on this device</button><button type="button" onClick={()=>setPreview(!preview)}>{preview?'Close preview':'Preview article'}</button></div><div className="aura-admin-publish"><label>Editor password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} /></label><button type="submit" disabled={busy||!edition?.configured||!password}>{busy?'Saving…':originalSlug?'Publish changes':'Publish article'}</button></div><p className="aura-ed-note">Load the published edition before publishing. Drafts stay on this device; publishing saves the article for every visitor. Reported claims must remain labelled as reported.</p></form>
 {preview && <article className="aura-article aura-admin-preview"><p className="aura-ed-kicker">Unpublished preview · {article.category}</p><h1>{article.title||'Your headline'}</h1><p className="aura-article-deck">{article.summary}</p><StoryImage key={article.image.src} article={article} /><div className="aura-article-body">{article.body.map((text,i)=><p key={i}>{text}</p>)}</div>{article.videoUrl&&<Video item={{name:'Related video',url:article.videoUrl,youtubeId:article.youtubeId,description:'Video attached to this story.'}} />}</article>}
 </main>;
}
