import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import '../styles/aura-editorial.css';
import '../styles/admin-articles.css';
import '../styles/aura-monetization.css';
export default function AdminMonetization(){
 const [config,setConfig]=useState(null),[revision,setRevision]=useState(null),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[configured,setConfigured]=useState(false);
 async function load(){setBusy(true);try{const r=await fetch('/api/monetization',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);const {revision:rev,configured:ok,...rest}=d;setConfig(rest);setRevision(rev);setConfigured(ok);setMessage(ok?'Commercial settings loaded.':'Settings loaded. Server publishing credentials still need configuring.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 useEffect(()=>{load();},[]);
 const partner=(key,field,value)=>setConfig(c=>({...c,partners:{...c.partners,[key]:{...c.partners[key],[field]:value}}}));
 const slot=(key,field,value)=>setConfig(c=>({...c,adSlots:{...c.adSlots,[key]:{...c.adSlots[key],[field]:value}}}));
 async function save(e){e.preventDefault();setBusy(true);try{const r=await fetch('/api/monetization',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${password}`},body:JSON.stringify({config,revision})});const d=await r.json();if(!r.ok)throw Error(d.error);const {revision:rev,configured:ok,...rest}=d;setConfig(rest);setRevision(rev);setConfigured(ok);setMessage('Monetisation settings published.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 if(!config)return <main className="aura-editorial aura-article-admin"><p role="status">Loading commercial settings…</p></main>;
 return <main className="aura-editorial aura-article-admin"><div className="aura-ed-kicker">AURA / Commercial Admin</div><h1>Monetisation.</h1><p>Manage affiliate destinations, ad inventory and disclosures without editing article code.</p><div className="aura-admin-toolbar"><Link to="/admin">Admin home</Link><Link to="/advertise">Advertise page</Link><button onClick={load} disabled={busy}>Reload</button></div>{message&&<p className="aura-admin-message" role="status">{message}</p>}<form onSubmit={save}>
 <h2>Partners</h2><div className="aura-admin-fields">{Object.entries(config.partners||{}).map(([key,p])=><div className="wide aura-admin-message" key={key}><strong>{p.name}</strong><label><input type="checkbox" checked={p.enabled} onChange={e=>partner(key,'enabled',e.target.checked)}/> Enabled</label><label>Official destination<input type="url" value={p.officialUrl||''} onChange={e=>partner(key,'officialUrl',e.target.value)}/></label><label>Affiliate tracking URL<input type="url" placeholder="Paste approved tracking link here" value={p.affiliateUrl||''} onChange={e=>partner(key,'affiliateUrl',e.target.value)}/></label><label>CTA text<input value={p.cta||''} onChange={e=>partner(key,'cta',e.target.value)}/></label></div>)}</div>
 <h2>Ad inventory</h2><div className="aura-admin-fields">{Object.entries(config.adSlots||{}).map(([key,s])=><div key={key} className="aura-admin-message"><strong>{key}</strong><label><input type="checkbox" checked={s.enabled} onChange={e=>slot(key,'enabled',e.target.checked)}/> Enabled</label><label>Mode<select value={s.mode} onChange={e=>slot(key,'mode',e.target.value)}><option value="house">House / direct sponsor</option><option value="adsense">AdSense</option><option value="off">Off</option></select></label><label>Label<input value={s.label||''} onChange={e=>slot(key,'label',e.target.value)}/></label></div>)}</div>
 <h2>AdSense</h2><div className="aura-admin-fields"><label><input type="checkbox" checked={config.adsense?.enabled===true} onChange={e=>setConfig(c=>({...c,adsense:{...c.adsense,enabled:e.target.checked}}))}/> Enable AdSense mode</label><label>Publisher client ID<input placeholder="ca-pub-…" value={config.adsense?.client||''} onChange={e=>setConfig(c=>({...c,adsense:{...c.adsense,client:e.target.value}}))}/></label><label className="wide">Affiliate disclosure<textarea value={config.disclosure||''} onChange={e=>setConfig(c=>({...c,disclosure:e.target.value}))}/></label></div>
 <div className="aura-admin-publish"><label>Editor password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy||!configured||!password}>{busy?'Saving…':'Publish monetisation settings'}</button></div>
 </form></main>;
}
