import Header from '../components/Header.jsx';
import Footer from '../components/Footer.jsx';
import { useEffect } from 'react';
import '../styles/aura-editorial.css';
import '../styles/aura-monetization.css';

function LegalFrame({title,kicker,children}) {
  useEffect(()=>{document.title=`${title} | AURA Fight Club`;window.scrollTo(0,0);},[title]);
  return <><Header/><main className="aura-editorial aura-ed-page"><section className="aura-advertise"><p className="aura-ed-kicker">{kicker}</p><h1>{title}.</h1>{children}</section></main><Footer/></>;
}
export function PrivacyPolicy(){
 return <LegalFrame title="Privacy policy" kicker="AURA / Privacy"><p>Last updated: 5 October 2026.</p><p>AURA Fight Club processes only the personal information needed to operate this website, respond to enquiries, administer editorial and commercial relationships, protect the service and understand aggregate site performance.</p><h2>Information we may receive.</h2><p>This can include information you submit directly, such as your name, email address and message, together with limited technical information generated when you use the site, such as device, page and security logs.</p><h2>Why we use it.</h2><p>We use information to answer enquiries, administer partnerships, maintain site security, operate requested services and meet legal obligations. Where consent is required for advertising or similar tracking technologies, they should not be activated until the relevant consent choice has been made.</p><h2>Third parties.</h2><p>Our hosting, email, analytics, advertising and affiliate partners may process limited information under their own terms and privacy notices. Clicking an external streaming, ticketing or retail link takes you to that provider's service.</p><h2>Your rights.</h2><p>Depending on where you live, you may have rights to access, correct, delete, restrict or object to processing of your personal information, and to withdraw consent where processing relies on consent.</p><h2>Contact.</h2><p>Privacy questions and rights requests can be sent to <a href="mailto:hello@aurafightclub.com">hello@aurafightclub.com</a>.</p></LegalFrame>;
}
export function CookiePolicy(){
 return <LegalFrame title="Cookie policy" kicker="AURA / Cookies"><p>Last updated: 5 October 2026.</p><p>AURA Fight Club uses technologies necessary to deliver and secure the website. Optional analytics, advertising or personalisation technologies may also be introduced as the site develops.</p><h2>Advertising.</h2><p>Google AdSense infrastructure is built into the site but advertising remains disabled until publisher approval and the required consent controls are configured. For visitors in territories where consent is required, non-essential advertising technologies should be governed by an appropriate consent management platform.</p><h2>Affiliate links.</h2><p>Affiliate partners may use their own cookies or similar technologies after you leave AURA and visit their websites. Their privacy and cookie policies apply to those services.</p><h2>Managing cookies.</h2><p>You can also remove or block cookies using your browser settings. Blocking strictly necessary technologies may affect parts of the site.</p><h2>Contact.</h2><p>Questions can be sent to <a href="mailto:hello@aurafightclub.com">hello@aurafightclub.com</a>.</p></LegalFrame>;
}
export function Terms(){
 return <LegalFrame title="Terms of use" kicker="AURA / Terms"><p>Last updated: 5 October 2026.</p><p>AURA Fight Club provides boxing news, analysis, commentary, fight information, video links and lifestyle content for general informational purposes.</p><h2>Editorial information.</h2><p>Fight dates, broadcast arrangements, rankings, ticket availability and prices can change. Readers should confirm time-sensitive information with the relevant promoter, sanctioning body, broadcaster or ticket provider before purchasing or travelling.</p><h2>External services.</h2><p>AURA may link to broadcasters, retailers, ticket sellers and other third parties. Unless expressly stated otherwise, transactions are completed with those third parties under their terms. AURA is not the seller of those third-party services.</p><h2>Commercial relationships.</h2><p>Some links may be affiliate links and some content or placements may be sponsored. These relationships are disclosed and do not grant advertisers control over editorial conclusions.</p><h2>Intellectual property.</h2><p>AURA's original branding, design and editorial material may not be republished commercially without permission. Third-party trademarks and credited source material remain the property of their respective owners.</p><h2>Contact.</h2><p>General enquiries: <a href="mailto:hello@aurafightclub.com">hello@aurafightclub.com</a>. Commercial enquiries: <a href="mailto:partnerships@aurafightclub.com">partnerships@aurafightclub.com</a>.</p></LegalFrame>;
}
